version: "2"

run:
  timeout: 5m

linters:
  # whitelist
  default: none
  enable:
    # 1. Default & Performa
    - govet # Inspeksi logika bawaan Go (pengganti go vet)
    - staticcheck # Perfeksionis performa (pengganti staticcheck manual)
    - ineffassign # Mendeteksi variabel yang diisi nilai tapi tidak pernah dipakai

    # 2. DevSecOps Suite
    - gosec # Auditor keamanan

    # 3. Resilience
    - errcheck # Memastikan tidak ada error yang diabaikan
    - bodyclose # Memastikan HTTP response body selalu ditutup untuk mencegah memory leak

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
