global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "secure-iam-api"
    scheme: https
    tls_config:
      insecure_skip_verify: true # Karena pakai self-signed certs
    static_configs:
      - targets: ["host.docker.internal:8443"]
